# Generated by js/scripts/generateJourneyAdapters.mjs from common/specs/journeys.yaml.
# Do not edit directly; run `npm run generate:journeys` from js/.

from typing import Final, Literal, TypeAlias, TypeGuard

from .journey_types import JourneySpec

JourneyId: TypeAlias = Literal["login-and-view-dashboard", "view-account-details"]
JOURNEY_IDS: Final[tuple[JourneyId, ...]] = (
    "login-and-view-dashboard",
    "view-account-details",
)
JOURNEY_SPECS: Final[dict[JourneyId, JourneySpec]] = {
    "login-and-view-dashboard": {
        "id": "login-and-view-dashboard",
        "name": "Login and View Dashboard",
        "description": "Basic happy-path login and dashboard visibility journey.",
        "successMessage": "Dashboard rendered",
        "extends": None,
        "preconditions": [
            "User exists in fixture data with valid credentials.",
            "Base application is reachable and renders the login form.",
        ],
        "steps": [
            {
                "action": "navigate",
                "path": "/",
            },
            {
                "action": "click",
                "selector": {
                    "first": False,
                    "by": "role",
                    "role": "link",
                    "name": {
                        "pattern": "sign in|log in",
                        "ignoreCase": True,
                    },
                    "level": None,
                },
            },
            {
                "action": "fill",
                "selector": {
                    "first": False,
                    "by": "label",
                    "name": {
                        "pattern": "email",
                        "ignoreCase": True,
                    },
                },
                "value": "user.email",
            },
            {
                "action": "fill",
                "selector": {
                    "first": False,
                    "by": "label",
                    "name": {
                        "pattern": "password",
                        "ignoreCase": True,
                    },
                },
                "value": "user.password",
            },
            {
                "action": "click",
                "selector": {
                    "first": False,
                    "by": "role",
                    "role": "button",
                    "name": {
                        "pattern": "sign in|log in",
                        "ignoreCase": True,
                    },
                    "level": None,
                },
            },
            {
                "action": "assert-visible",
                "selector": {
                    "first": False,
                    "by": "role",
                    "role": "heading",
                    "name": {
                        "pattern": "dashboard",
                        "ignoreCase": True,
                    },
                    "level": 1,
                },
            },
            {
                "action": "assert-visible",
                "selector": {
                    "first": False,
                    "by": "testId",
                    "value": "account-summary",
                },
            },
        ],
    },
    "view-account-details": {
        "id": "view-account-details",
        "name": "View Account Details",
        "description": "Navigate to an account details page from dashboard.",
        "successMessage": "Account details rendered",
        "extends": "login-and-view-dashboard",
        "preconditions": [
            "Logged in user with at least one account.",
            "Dashboard lists accounts with a stable test id.",
        ],
        "steps": [
            {
                "action": "click",
                "selector": {
                    "first": True,
                    "by": "testId",
                    "value": "account-list-item",
                },
            },
            {
                "action": "assert-visible",
                "selector": {
                    "first": False,
                    "by": "role",
                    "role": "heading",
                    "name": {
                        "pattern": "account details",
                        "ignoreCase": True,
                    },
                    "level": 1,
                },
            },
            {
                "action": "assert-visible",
                "selector": {
                    "first": False,
                    "by": "testId",
                    "value": "transaction-table",
                },
            },
        ],
    },
}


def is_journey_id(value: str) -> TypeGuard[JourneyId]:
    return value in JOURNEY_IDS
