import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import process from 'node:process';

import { parse } from 'yaml';
import * as z from 'zod/v4';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, '../..');

const textMatcherSchema = z.object({
  values: z.array(z.string().min(1)).min(1),
  ignoreCase: z.boolean().optional().default(false),
  exact: z.boolean().optional().default(false)
}).strict();

const selectorBaseShape = {
  first: z.boolean().optional().default(false)
};

const selectorSchema = z.discriminatedUnion('by', [
  z.object({
    ...selectorBaseShape,
    by: z.literal('role'),
    role: z.enum(['button', 'heading', 'link']),
    name: textMatcherSchema.optional().nullable().default(null),
    level: z.number().int().positive().optional().nullable().default(null)
  }).strict(),
  z.object({
    ...selectorBaseShape,
    by: z.literal('label'),
    name: textMatcherSchema
  }).strict(),
  z.object({
    ...selectorBaseShape,
    by: z.literal('testId'),
    value: z.string().min(1)
  }).strict()
]);

const stepSchema = z.discriminatedUnion('action', [
  z.object({
    action: z.literal('navigate'),
    path: z.string().startsWith('/')
  }).strict(),
  z.object({
    action: z.literal('click'),
    selector: selectorSchema
  }).strict(),
  z.object({
    action: z.literal('fill'),
    selector: selectorSchema,
    value: z.enum(['user.email', 'user.password', 'user.displayName'])
  }).strict(),
  z.object({
    action: z.literal('assert-visible'),
    selector: selectorSchema
  }).strict()
]);

const journeySchema = z.object({
  id: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  name: z.string().min(1),
  description: z.string().min(1),
  successMessage: z.string().min(1),
  extends: z.string().optional().nullable().default(null),
  preconditions: z.array(z.string().min(1)).default([]),
  steps: z.array(stepSchema).min(1)
}).strict();

const documentSchema = z.object({
  version: z.literal(1),
  journeys: z.array(journeySchema).min(1)
}).strict();

const validateJourneyGraph = (document) => {
  const journeyIds = new Set();
  for (const journey of document.journeys) {
    if (journeyIds.has(journey.id)) {
      throw new Error(`Duplicate journey id: ${journey.id}`);
    }
    journeyIds.add(journey.id);
  }

  for (const journey of document.journeys) {
    if (journey.extends !== null && !journeyIds.has(journey.extends)) {
      throw new Error(`Journey ${journey.id} extends unknown journey: ${journey.extends}`);
    }
  }

  const byId = new Map(document.journeys.map((journey) => [journey.id, journey]));
  for (const journey of document.journeys) {
    const chain = [];
    let current = journey;
    while (current.extends !== null) {
      if (chain.includes(current.id)) {
        throw new Error(`Journey inheritance cycle: ${[...chain, current.id].join(' -> ')}`);
      }
      chain.push(current.id);
      current = byId.get(current.extends);
    }
  }

  return document;
};

export const parseJourneyDocument = (source) => {
  const parsed = typeof source === 'string' ? parse(source) : source;
  return validateJourneyGraph(documentSchema.parse(parsed));
};

const generatedHeader = (comment) =>
  `${comment} Generated by js/scripts/generateJourneyAdapters.mjs from common/specs/journeys.yaml.\n` +
  `${comment} Do not edit directly; run \`npm run generate:journeys\` from js/.\n\n`;

export const generateTypeScript = (document) => {
  const ids = document.journeys.map(({ id }) => id);
  const specs = Object.fromEntries(document.journeys.map((journey) => [journey.id, journey]));

  return `${generatedHeader('//')}import type { JourneySpec } from './journeyTypes.js';

export const journeyIds = ${JSON.stringify(ids, null, 2)} as const;
export type JourneyId = (typeof journeyIds)[number];

export const journeySpecs: Readonly<Record<JourneyId, JourneySpec>> = ${JSON.stringify(specs, null, 2)};

export const isJourneyId = (value: string): value is JourneyId =>
  (journeyIds as readonly string[]).includes(value);
`;
};

const pythonString = (value) => JSON.stringify(value, null, 0);

const pythonLiteral = (value, indentation = 0) => {
  if (value === null) return 'None';
  if (typeof value === 'boolean') return value ? 'True' : 'False';
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') return pythonString(value);

  const prefix = ' '.repeat(indentation);
  const childPrefix = ' '.repeat(indentation + 4);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map((item) => `${childPrefix}${pythonLiteral(item, indentation + 4)},`).join('\n')}\n${prefix}]`;
  }

  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  return `{\n${entries
    .map(([key, item]) => `${childPrefix}${pythonString(key)}: ${pythonLiteral(item, indentation + 4)},`)
    .join('\n')}\n${prefix}}`;
};

export const generatePython = (document) => {
  const ids = document.journeys.map(({ id }) => id);
  const specs = Object.fromEntries(document.journeys.map((journey) => [journey.id, journey]));
  const literalIds = ids.map(pythonString).join(', ');

  return `${generatedHeader('#')}from typing import Final, Literal, TypeAlias, TypeGuard

from .journey_types import JourneySpec

JourneyId: TypeAlias = Literal[${literalIds}]
JOURNEY_IDS: Final[tuple[JourneyId, ...]] = (\n${ids.map((id) => `    ${pythonString(id)},`).join('\n')}\n)
JOURNEY_SPECS: Final[dict[JourneyId, JourneySpec]] = ${pythonLiteral(specs)}


def is_journey_id(value: str) -> TypeGuard[JourneyId]:
    return value in JOURNEY_IDS
`;
};

export const buildGeneratedAdapters = (source) => {
  const document = parseJourneyDocument(source);
  return {
    typescript: generateTypeScript(document),
    python: generatePython(document)
  };
};

const targets = [
  {
    key: 'typescript',
    path: path.join(repositoryRoot, 'js/src/lib/journeys/generatedJourneySpecs.ts')
  },
  {
    key: 'python',
    path: path.join(repositoryRoot, 'py/src/playwright_adventures/journeys/generated_specs.py')
  }
];

export const generateAdapters = async ({ check = false } = {}) => {
  const source = await readFile(path.join(repositoryRoot, 'common/specs/journeys.yaml'), 'utf8');
  const generated = buildGeneratedAdapters(source);
  const stale = [];

  for (const target of targets) {
    const content = generated[target.key];
    if (check) {
      const existing = await readFile(target.path, 'utf8').catch(() => null);
      if (existing !== content) stale.push(path.relative(repositoryRoot, target.path));
    } else {
      await writeFile(target.path, content, 'utf8');
    }
  }

  if (stale.length > 0) {
    throw new Error(
      `Generated journey adapters are stale: ${stale.join(', ')}. Run \`npm run generate:journeys\` from js/.`
    );
  }
};

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateAdapters({ check: process.argv.includes('--check') }).catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
