// Generated by js/scripts/generateJourneyAdapters.mjs from common/specs/journeys.yaml.
// Do not edit directly; run `npm run generate:journeys` from js/.

import type { JourneySpec } from './journeyTypes.js';

export const journeyIds = [
  "login-and-view-dashboard",
  "view-account-details"
] as const;
export type JourneyId = (typeof journeyIds)[number];

export const journeySpecs: Readonly<Record<JourneyId, JourneySpec>> = {
  "login-and-view-dashboard": {
    "id": "login-and-view-dashboard",
    "name": "Login and View Dashboard",
    "description": "Basic happy-path login and dashboard visibility journey.",
    "successMessage": "Dashboard rendered",
    "extends": null,
    "preconditions": [
      "User exists in fixture data with valid credentials.",
      "Base application is reachable and renders the login form."
    ],
    "steps": [
      {
        "action": "navigate",
        "path": "/"
      },
      {
        "action": "click",
        "selector": {
          "first": false,
          "by": "role",
          "role": "link",
          "name": {
            "values": [
              "sign in",
              "log in"
            ],
            "ignoreCase": true,
            "exact": false
          },
          "level": null
        }
      },
      {
        "action": "fill",
        "selector": {
          "first": false,
          "by": "label",
          "name": {
            "values": [
              "email"
            ],
            "ignoreCase": true,
            "exact": false
          }
        },
        "value": "user.email"
      },
      {
        "action": "fill",
        "selector": {
          "first": false,
          "by": "label",
          "name": {
            "values": [
              "password"
            ],
            "ignoreCase": true,
            "exact": false
          }
        },
        "value": "user.password"
      },
      {
        "action": "click",
        "selector": {
          "first": false,
          "by": "role",
          "role": "button",
          "name": {
            "values": [
              "sign in",
              "log in"
            ],
            "ignoreCase": true,
            "exact": false
          },
          "level": null
        }
      },
      {
        "action": "assert-visible",
        "selector": {
          "first": false,
          "by": "role",
          "role": "heading",
          "name": {
            "values": [
              "dashboard"
            ],
            "ignoreCase": true,
            "exact": false
          },
          "level": 1
        }
      },
      {
        "action": "assert-visible",
        "selector": {
          "first": false,
          "by": "testId",
          "value": "account-summary"
        }
      }
    ]
  },
  "view-account-details": {
    "id": "view-account-details",
    "name": "View Account Details",
    "description": "Navigate to an account details page from dashboard.",
    "successMessage": "Account details rendered",
    "extends": "login-and-view-dashboard",
    "preconditions": [
      "Logged in user with at least one account.",
      "Dashboard lists accounts with a stable test id."
    ],
    "steps": [
      {
        "action": "click",
        "selector": {
          "first": true,
          "by": "testId",
          "value": "account-list-item"
        }
      },
      {
        "action": "assert-visible",
        "selector": {
          "first": false,
          "by": "role",
          "role": "heading",
          "name": {
            "values": [
              "account details"
            ],
            "ignoreCase": true,
            "exact": false
          },
          "level": 1
        }
      },
      {
        "action": "assert-visible",
        "selector": {
          "first": false,
          "by": "testId",
          "value": "transaction-table"
        }
      }
    ]
  }
};

export const isJourneyId = (value: string): value is JourneyId =>
  (journeyIds as readonly string[]).includes(value);
